#!/usr/bin/env bash

# this is a simple config for herbstluftwm
. ~/.config/herbstluftwm/theme-dark.conf

hc() {
    herbstclient "$@"
}

hc emit_hook reload

xsetroot -solid '#252525'

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Mod4

# tags
#tag_names=( {1..9} 0 )
tag_names=( "" "" "" "" "" "" "" " " "" )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in ${!tag_names[@]} ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key" use_index "$i"
        hc keybind "$Mod-Shift-$key" move_index "$i"
    fi
done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.

hc keybind $Mod-space                                                           \
            or , and . compare tags.focus.curframe_wcount = 2                   \
                     . cycle_layout +1 vertical horizontal max vertical grid    \
               , cycle_layout +1

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent

# theme color
hc set frame_border_active_color ${FBAC}
hc set frame_border_normal_color ${FBNC}
hc set frame_bg_normal_color ${FBGNC}
hc set frame_bg_active_color ${FBGAC}
hc attr theme.active.color ${TAC}
hc attr theme.normal.color ${TNC}
hc attr theme.urgent.color ${TUC}
hc attr theme.inner_color ${TIC}
hc attr theme.floating.outer_color ${TFO}
hc attr theme.active.inner_color ${TAIC}
hc attr theme.active.outer_color ${TAOC}
hc attr theme.background_color ${TBC}

# theme layout
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 20
hc set frame_border_width 0
hc set always_show_frame 0
hc set frame_bg_transparent 1
hc set frame_transparent_width 0
hc set frame_gap 5
hc attr theme.inner_width 0
hc attr theme.border_width 0
hc attr theme.floating.border_width 3
hc attr theme.floating.outer_width 3

hc set window_gap 5
hc set frame_padding 2
hc set smart_window_surroundings 0
hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 1

# rules
hc unrule -F
hc rule class=chromium             tag=
hc rule class=XTerm                tag=
hc rule class=telegram             tag=
hc rule class=URxvt                tag=
hc rule class=Nautilus 			   tag=
hc rule focus=on

#hc rule focus=off # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
#hc set_monitors 1366x768+0+0 1360x768+1360+0
# or simply:
hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=/etc/xdg/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    "$panel" $monitor &
done

# Wallpaper
feh --bg-fill ~/.i3/backgrounds/blury_mountains.jpg

