#! /bin/sh

HEIGHT=24
#FONT="-xos4-terminesspowerline-medium-r-normal--12-120-72-72-c-60-iso10646-1"
#FONT_ICON="-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1"

# icons
GENTOO="\uf2bd"
ARCH="\ue00e"
CSTART="\ue00d"
CSOUND="\ue04d"
CVOLUME="\ue204"
CMAIL="\ue070"
CCPU="\ue026"
CRAM="\ue021"
CNET="\ue04b"
CWIFI="\ue222"
WIFI_STR="\ue02d"
CWS="\uf10c"
CIP=" ++ "
TOR="\ue1f7"
# Time
CTIME="\ue018"
CPACK="\ue1b7"
CCLOCK="\ue016"
# panel center
CNONE="\uf192"
#CNONE="\ue023"

#CFULL="\ue0c1"
CFULL="\ue022"

# icons panel music
CPREV="\ue055"
CNEXT="\ue05b"
CPLAY="\ue058"
CPAUS="\ue059"
# icon volume
VPLUS="\ue06c"
VMINUS="\ue06d"
# battery or AC
BAT100="\ue03f"
BAT70="\ue03f"
BAT50="\ue03e"
BAT30="\ue03e"
BAT15="\ue03d"
BAT7="\ue03c"
CAC="\ue040"
## programs
URXVT="\uf120"
XTERM="\uf120"
CHROME="\uf268"
DESK="\uf108"
FILEM="\uf07b"


# $(pAction ${fg} ${bg} ${${command} ${whatprint})
pAction() {
    echo "%{F$1}%{B$2}%{A:$3:}$(printf '%b' $4)%{A}%{B-}%{F-}"
}

# $(pActionUnderline ${fg} ${bg} ${underline} ${${command} ${whatprint})
pActionUnderline() {
    echo "%{F$1}%{B$2}%{U$3}%{+u}%{A:$4:}$(printf '%b' $5)%{A}%{-u}%{B-}%{F-}"
}

# $(pIcon ${color} ${icon})
pIcon() {
    echo "%{F$1}$(printf '%b' $2)%{F-}"
}

# $(pIconUnderline ${color} ${color_underline} ${icon})
pIconUnderline() {
    echo "%{F$1}%{U$2}%{+u}$(printf '%b' $3)%{-u}%{F-}"
}

# $(pText ${color} ${text})
pText() {
    echo "%{F$1}$2%{F-}"
}

# $(pTextUnderline ${color} ${color_underline} ${text})
pTextUnderline() {
    echo "%{F$1}%{U$2}%{+u}$3%{-u}%{F-}"
}

getXresColor() {
   echo "$( xrdb -query | grep $1: | grep -oE '#[a-zA-Z0-9]{6}' | cut -c 1- | sed -e 's/#/#FF/g' )"
}

getIcon () {
		wnd_focus=$(xdotool getwindowfocus)
        wnd_title=$(xprop -id $wnd_focus WM_CLASS | grep -Po "\".*?\"" | head -1 | grep -Po "[^\"]*" )
		if [[ "$wnd_title" == '' ]]; then
                wnd_title='desktop'
		fi
        if [[ "$wnd_title" == 'urxvt' ]]; then
                echo "\uf120"
        elif [[ "$wnd_title" == 'xterm' ]]; then
                echo "\uf120"
        elif [[ "$wnd_title" == 'chromium' ]]; then
                echo "\uf268"
        elif [[ "$wnd_title" == 'Google Chrome' ]]; then
                 echo "\uf268"
        elif [[ "$wnd_title" == 'firefox' ]]; then
                echo "\uf269"
        elif [[ "$wnd_title" == 'desktop' ]]; then
               echo "\uf108"
        elif [[ "$wnd_title" == 'nautilus' ]]; then
                echo "\uf07b"
        elif [[ "$wnd_title" == 'atom' ]]; then
                echo "\uf121"
        elif [[ "$wnd_title" == 'spotify' ]]; then
                echo "\uf1bc"
        elif [[ "$wnd_title" == 'Telegram' ]]; then
                echo "\uf2c6"
        else
                echo "\uf17c"
        fi
}

# colors
BG="$(getXresColor background)"
fg="$(getXresColor foreground)" #fix for panel_bar
FG="$(getXresColor foreground)"
BLACK="$(getXresColor color0)"
BLACK2="$(getXresColor color8)"
RED="$(getXresColor color1)"
RED2="$(getXresColor color9)"
GREEN="$(getXresColor color2)"
GREEN2="$(getXresColor color10)"
YELLOW="$(getXresColor color3)"
YELLOW2="$(getXresColor color11)"
BLUE="$(getXresColor color4)"
BLUE2="$(getXresColor color12)"
MAGENTA="$(getXresColor color5)"
MAGENTA2="$(getXresColor color13)"
CYAN="$(getXresColor color6)"
CYAN2="$(getXresColor color14)" 
WHITE="$(getXresColor color7)"
WHITE2="$(getXresColor color15)"
