#! /bin/bash
#

source $(dirname $0)/config_bar
source $(dirname $0)/panel_colors
#source $(dirname $0)/panel_icons

num_mon=$(bspc query -M | wc -l)

while read -r line ; do
        case $line in
                S*)
                        #sys="%{F$COLOR_SYS_FG}%{B$COLOR_SYS_BG} ${line#?} %{B-}%{F-}"
                        sysR="${line#?}"
                        ;;
                T*)
                        #title="%{F$COLOR_TITLE_FG}%{B$COLOR_TITLE_BG} ${line#?} %{B-}%{F-}"
                        sysL="${line#?}"
                        ;;
                W*)
                        # bspwm's state
                        wm=""
                        IFS=':'
                        set -- ${line#?}
                        while [ $# -gt 0 ] ; do
                                item=$1
                                name=${item#?}
                                case $item in
                                        [mM]*)
                                                [ $num_mon -lt 2 ] && shift && continue
                                                case $item in
                                                        m*)
                                                                # monitor
                                                                FG=$FG
                                                                BG=$BG
                                                                ;;
                                                        M*)
                                                                # focused monitor
                                                                FG=$fg
                                                                BG=$BG
                                                                ;;
                                                esac
                                                wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc monitor -f ${name}:} ${name} %{A}%{B-}%{F-}"
                                                ;;
                                        [fFoOuU]*)
                                                case $item in
                                                        f*)
                                                                # free desktop
                                                                FG=$fg
                                                                IC=${CWS}
                                                                BG=$BG
                                                                ;;
                                                        F*)
                                                                # focused free desktop
                                                                FG=$MAGENTA
                                                                IC=${CNONE}
                                                                BG=$BG
                                                                ;;
                                                        o*)
                                                                # occupied desktop
                                                                FG=$RED
                                                                IC=${CWS}
                                                                BG=$BG
                                                                ;;
                                                        O*)
                                                                # focused occupied desktop
                                                                FG=$MAGENTA
                                                                IC=${CNONE}
                                                                BG=$BG
                                                                ;;
                                                        u*)
                                                                # urgent desktop
                                                                FG=$YELLOW
                                                                IC=${CNONE}
                                                                BG=$BG
                                                                ;;
                                                        U*)
                                                                # focused urgent desktop
                                                                FG=$YELLOW
                                                                IC=${CFULL}
                                                                BG=$BG
                                                                ;;
                                                esac
                                                wm="${wm}%{F${FG}}%{B${BG}}%{A:bspc desktop -f ${name}:}  $(printf '%b' $IC) %{A}%{B-}%{F-}"
                                                ;;
                                        [LTG]*)
                                                # layout, state and flags
                                                wm="${wm}%{F$FG}%{F-}"
                                                ;;
                                esac
                                shift
                        done
                        ;;
        esac
        printf "%s\n" "%{l}${sysL}%{c}${wm}%{r}${sysR}"
done
