#! /bin/sh

#FONTS
FONT="TerminessTTF Nerd Font Mono:style=Medium:pixelsize=13.5:antialias=true:hinting=true"
ICONS="Wuncon Siji:style=Regular:pixelsize=10"

#SIZES
BARHEIGHT=20
EDGEWIDTH=0
UNDERLINE_WIDTH=2

# Don't touch.  Edit width/height above instead.
SCREENHEIGHT=$(xrandr -q | grep Screen | awk '{print $10}' | sed s/,//)
SCREENWIDTH=$(xrandr -q | grep Screen | awk '{print $8}')
BARWIDTH=$(($SCREENWIDTH - $(($EDGEWIDTH * 2))))


source $(dirname $0)/panel_colors
source $(dirname $0)/config_bar

#if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
#	printf "%s\n" "The panel is already running." >&2
#	exit 1
#fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc config top_padding $PANEL_HEIGHT
bspc subscribe |\
        grep -oE "[Mm][^TM]*[TML]" --line-buffered |\
        while read line; do echo W$line; done > "$PANEL_FIFO" &

{

getName() {
        #local ICON=$(getIcon)
        local icon=$(pIcon ${FG} ${GENTOO})
        local cmd="$(uname -n)"
        #local cmdEnd=$(pText ${WHITE} "${cmd}")
        local cmdEnd=$(pTextUnderline ${WHITE} ${MAGENTA2} "${cmd}" )
        echo " ${cmdEnd}"
}


getMyIp() {
        local icon=$(pIcon ${MAGENTA2} ${CIP})
        local cmd="$(curl -s https://ifcfg.me/)"
        local cmdEnd=$(pText ${FG} "${cmd}")
        echo "${icon} ${cmdEnd} ${icon}"
}

ram() {
        local icon=$(pIcon ${MAGENTA2} ${CRAM})
        local cmd=`free | awk '/Mem:/ {print int($3/$2 * 100.0)}'`
        local cmdEnd=$(pText ${FG} "${cmd}")
        echo "${icon} ${cmdEnd}%"
}


cpu() {
        local icon=$(pIcon ${MAGENTA} ${CCPU})
        local cmd=" $(cat /proc/loadavg | awk '{print $1}')"
        #local cmd=$(grep 'cpu ' /proc/stat | awk '{usage=($2+$4)*100/($2+$4+$5)} END {print usage}')
        #local cmd+=$(printf "%.0f" $usage)
        local cmd+=" $(cat /proc/loadavg | awk '{print $4}')"
        local clr=$(pText ${FG} "${cmd}")%
        echo "${icon} ${clr}"
}

music() {
        local icon=$(pIcon ${MAGENTA2} ${CIP})
        local stat="$(mpc status | grep \# | awk '{print $1}')"
        local artist=$(mpc -f %artist% current)
        local musicname=$(mpc -f %title% current)
        local cmd=""
        if [ "${stat}" ] && [ "${stat}" = "[playing]" ] ; then
                local cmd="Playing >> ${artist:0:10} - ${musicname:0:15}"
        elif [ "${stat}" ] && [ "${stat}" = "[paused]" ] ; then
                local cmd="Paused >> ${artist:0:10} - ${musicname:0:20}"
        else
                local cmd="No Sound"
        fi
        local cmdEnd=$(pText ${FG} "${cmd}")
        echo "${icon} ${cmdEnd} ${icon}"
}

getDay() {
        local icon=$(pIcon ${MAGENTA} ${CTIME})
        local cmd=" $(date '+%A %d %b')" 
        local cmdEnd=$(pText ${FG} "${cmd}")
        echo "${icon}${cmdEnd}"
}

clock() {
        local icon=$(pIcon ${MAGENTA} ${CCLOCK})
        local cmd=$(date +%H:%M)
        local cmdEnd=$(pText ${FG} ${cmd})
        echo "${icon} ${cmdEnd}"
}

mail() {
        local gmaildir=/home/user/.mails/Gmail/\[Gmail\].All\ Mail/new
        local cmd=$(pAction ${BLUE} ${BG} "i3 'exec termite -e mutt'" ${CMAIL})
        local count=0
        if [[ ! -n $(ls "${gmaildir}") ]]; then
                count=0
        else
                count=$(ls -1 "${gmaildir}" | wc -l)
        fi
        echo "${cmd} ${count}"
}

energy() {
    local ac=/sys/class/power_supply/AC/online
    local bat=/sys/class/power_supply/BAT0/present
    local icon=""
    local batCap=""
    if [[ -e $bat ]] && [[ $(cat $ac) -lt 1 ]]; then
            batCap1="$(cat ${bat%/*}/capacity)%"
            batCap="$(cat ${bat%/*}/capacity)"
            [ $batCap -ge 90 ] && icon=$BAT100
            [ $batCap -ge 70 ] && [ $batCap -le 90 ] && icon=$BAT70
            [ $batCap -ge 50 ] && [ $batCap -le 70 ] && icon=$BAT50
            [ $batCap -ge 30 ] && [ $batCap -le 50 ] && icon=$BAT30
            [ $batCap -ge 15 ] && [ $batCap -le 30 ] && icon=$BAT15
            [ $batCap -le 7 ] && icon=$BAT7
    elif [[ -n $(cat $ac) ]]; then
            batCap1="AC"
            icon=$CAC
    else
            batCap1="wttf"
    fi
    echo "$(pIcon ${MAGENTA} $icon) $(pText ${FG} ${batCap1})"
}
while :; do
        echo "S %{F$FG} \
                %{l} $(getName)  $(music)\
                %{r}$(energy) $(ram) $(cpu) $(getDay) $(clock) "
        sleep .5
done
} > "$PANEL_FIFO" &

$(dirname $0)/panel_bar < "$PANEL_FIFO" | lemonbar \
        -a 32 \
        -n "$PANEL_WM_NAME" \
        -g ${BARWIDTH}x${BARHEIGHT}+${EDGEWIDTH} \
        -u 2 \
        -f "${FONT}" \
        -f "${ICONS}" \
        -F "$FG" \
        -B "$BG" | sh | while read line; do eval "$line"; done &

wid=$(xdo id -a "$PANEL_WM_NAME")
tries_left=20
while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
	sleep 0.05
	wid=$(xdo id -a "$PANEL_WM_NAME")
	tries_left=$((tries_left - 1))
done
[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
