#! /bin/sh

#bspc monitor LVDS -d    

bspc monitor LVDS -d I III
bspc monitor HDMI-0 -d II
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a XTerm desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc config focus_follows_pointer true

bspc config normal_border_color '#917154'
bspc config focused_border_color '#BA5E57'
bspc config presel_border_color '#9a875f'
bspc config normal_sticky_border_color '#8abeb7'
bspc config focused_sticky_border_color '#282828'
bspc config urgent_border_color '#b76969'
xsetroot -cursor_name left_ptr
feh --bg-fill ~/backgrounds/gits.png
~/.themes/Flat/flat.sh &
sxhkd -c ~/.themes/sxhkd/bspwm/sxhkdrc
