#! /bin/sh

bspc monitor -d I II III IV V VI
gap=8

export GDK_SCALE=2 &
export GDK_DPI_SCALE=0.4 &

#This creates negative padding eaual to window gap so that gaps are shown only between windows and not on desktop edges.
bspc config window_gap $gap
bspc config top_padding $(($PANEL_HEIGHT-$gap))
for side in right bottom left ; do
	bspc config ${side}_padding -$gap
done
bspc config border_width    0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config history_aware_focus     true
bspc config adaptive raise          true

bspc rule -a Google-chrome desktop='^1' private=on
bspc rule -a XTerm desktop='^2'
bspc rule -a XTerm:ncmpcpp state=floating
bspc rule -a Nautilus desktop='^3'
bspc rule -a Spotify desktop='^4'
bspc rule -a Gimp desktop='^5' state=pseudo_tiled follow=on
bspc config focus_follows_pointer true

bspc config normal_border_color "#FF782e43"
bspc config focused_border_color "#746081"
bspc config presel_feedback_color "#746081"

xsetroot -cursor_name left_ptr
feh --bg-fill ~/Imágenes/12.png
sxhkd -c ~/.themes/bspwm/sxhkd/sxhkdrc &
~/.themes/bspwm/dragon/panel
