#!/bin/bash -

STATUS=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "state" | awk '{print $2}')
BATERY=$(upower -i /org/freedesktop/UPower/devices/battery_BAT0 | grep -E "percentage" | awk '{print $2}' | cut -d '%' -f 1)
SECURELEVEL='40'

Batery(){
        if [[ $BATERY -lt $SECURELEVEL ]]; then
                if [[ $STATUS == "discharging" ]]; then
                        notify-send -u critical 'Batery Low!' 'connect the charger!!.'
                fi
        fi
}

# Batery Loop
while true; do Batery; sleep 60; done
